name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --noconsole --onefile Login.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: social-media-app-exe
        path: dist/Login.exe
